### ISSUE TITLE
Timeout due to kakao bot limit (3s)

### ISSUE THREAD

**Issue by Beomi** [Beomi/where-is-my-customs#2]
카카오톡 봇 API 서버에서 응답 처리 속도 제한 (3초)로 인해 생기는 Timeout 이슈

# TODO

- [ ] 현재 배포된 API 서버 테스트
  - [ ] locust Test
- [ ] 처리 속도 최적화

# Maybe

- [ ] 서버리스 플랫폼으로 마이그레이션

**Comment by turlvo** [comment]
안녕하세요. 
BotHub.Studio를 운영하고 있는 DeepNatural의 박연호라고합니다.

Beomi님께서 만드신 '내 통관은 어디쯤?' 이라는 챗봇을 보고 유용해 보여서,
저희 BotHub.Studio라는 플랫폼에 Beomi님의 소스를 참고하여 카카오톡, 텔레그램, 슬랙에 연동해 보았습니다.
https://github.com/turlvo/where-is-my-customs

BotHub.Studio는 Heroku와 같이 직접 서버를 운영 할 필요도 없고,
Python언어로 한번의 개발을 통해 다양한 채널에 바로 연동 가능한 장점이 있습니다.
추후 유용한 챗봇을 제작할 계획이 있으시면 이용해봐주세요~~~

고맙습니다.
